apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-registry-data
  annotations:
    "volume.alpha.kubernetes.io/node-affinity": '{
      "requiredDuringSchedulingIgnoredDuringExecution": {
        "nodeSelectorTerms": [
          { "matchExpressions": [
            { "key": "kubernetes.io/hostname",
              "operator": "In",
              "values": ["192.168.199.142"]
            }
          ]}
         ]}
        }'
spec:
  capacity:
    storage: 200Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: harbor-local-storage
  local:
    path: /data/harbor-registry