apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "harbor-jobservice"
  labels:
    app: harbor
    component: jobservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor
      component: jobservice
  template:
    metadata:
      labels:
        app: harbor
        component: jobservice
    spec:
      containers:
      - name: jobservice
        image: vmware/harbor-jobservice:v1.4.0
        envFrom:
        - secretRef:
            name: "harbor-jobservice"
        env:
          - name: LOG_LEVEL
            value: debug
          - name: CONFIG_PATH
            value: /etc/jobservice/app.conf
          - name: GODEBUG
            value: netdns=cgo
          - name: ADMINSERVER_URL
            value: "http://harbor-adminserver"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jobservice-config
          mountPath: /etc/jobservice/app.conf
          subPath: app.conf
        - name: jobservice-secrets
          mountPath: /etc/jobservice/key
          subPath: key
        - name: job-logs
          mountPath: /var/log/jobs
      volumes:
      - name: jobservice-config
        configMap:
          name: "harbor-jobservice"
      - name: jobservice-secrets
        secret:
          secretName: "harbor-jobservice"
          items:
            - key: secretKey
              path: key
      - name: job-logs
        emptyDir: {}
