apiVersion: v1
kind: Secret
metadata:
  name: "harbor-jobservice"
  labels:
    app: harbor
type: Opaque
data:
  # echo -n "not-a-secure-secret" | base64
  secretKey: bm90LWEtc2VjdXJlLWtleQ==
  # echo -n "not-a-secure-secret" | base64
  JOBSERVICE_SECRET: bm90LWEtc2VjdXJlLWtleQ==
  # echo -n "not-a-secure-secret" | base64
  UI_SECRET: bm90LWEtc2VjdXJlLWtleQ==