apiVersion: v1
kind: Secret
metadata:
  name: harbor-adminserver
  labels:
    app: harbor
    component: adminserver
type: Opaque
data:
  # echo -n "not-a-secure-key" | base64
  # The secret key used for encryption. Must be a string of 16 chars.
  secretKey: bm90LWEtc2VjdXJlLWtleQ==
  # echo -n "xxxxxx" | base64
  EMAIL_PWD: xxxx
  # echo -n "xxxxx" | base64
  HARBOR_ADMIN_PASSWORD: xxxx
  # echo -n "xxxxxx" | base64
  MYSQL_PWD: xxxx
  # echo -n "not-a-secure-secret" | base64
  JOBSERVICE_SECRET: bm90LWEtc2VjdXJlLWtleQ==
  # echo -n "not-a-secure-secret" | base64
  UI_SECRET: bm90LWEtc2VjdXJlLWtleQ==