apiVersion: v1
kind: ConfigMap
metadata:
  name: "harbor-ui"
  labels:
    app: harbor
data:
  app.conf: |+
    appname = Harbor
    runmode = prod
    enablegzip = true
    [prod]
    httpport = 8080
